### ISSUE TITLE
Make it run on Windows

### ISSUE THREAD

**Issue by eriklax** [halonsecurity/halonctl#21]
Currently the only issue is that Terminal (used in cmd.py) is not supported on windows, causing halonctl to fail during start (due to autoload of module). Removing cmd.py causes other commands to work

```from blessings import Terminal```

Tested on Python 3 on Windows 7.

**Comment by uppfinnarn** [comment]
This should work on Windows as well, if the module is installed properly - can I have a backtrace for when the module is present?

**Comment by eriklax** [comment]
```
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Erik Lax\halonctl-master\halonctl\__main__.py", line 303, in <m
odule>
    main()
  File "C:\Users\Erik Lax\halonctl-master\halonctl\__main__.py", line 204, in ma
in
    load_modules(os.path.join(path, 'modules'))
  File "C:\Users\Erik Lax\halonctl-master\halonctl\__main__.py", line 52, in loa
d_modules
    mod = loader.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\Erik Lax\halonctl-master\halonctl\modules\cmd.py", line 5, in <
module>
    from blessings import Terminal
  File "C:\Python34\lib\site-packages\blessings\__init__.py", line 5, in <module
>
    import curses
  File "C:\Python34\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'
```

**Comment by uppfinnarn** [comment]
> No one has made a Windows port of the curses module.
> – the [curses module docs](https://docs.python.org/2/howto/curses.html#what-is-curses)

Welp, that breaks `blessings` there. Since all the  used for is to get viewport dimensions, I should look for another way to get this in a portable way - Windows' console has to have *some* kind of `terminfo` quivalent.

**Comment by eriklax** [comment]
I think an acceptable solution would be to downgrade the UX for Windows users in the cmd module (that is of course if it could be done conditionally).

**Comment by uppfinnarn** [comment]
Alternatively, make a function in `util.py` that returns a tuple of `(x, y)` with the terminal dimensions, something like:

```
def viewport_size():
    try:
        from blessings import Terminal
        # ...
    except ImportError:
        return (80, 25)
```

Windows' cmd.exe refuses to go wider than 80 characters, as 80x25 is the standard size for those good ol' IBM VGA terminals, and it's also the standard size basically every terminal emulator in use (`Terminal.app`, `iTerm2.app`, `gnome-terminal`, etc) opens at, so it's a reasonably safe default.

**Comment by eriklax** [comment]
Yep, that sounds like a very good idea!

**Comment by uppfinnarn** [comment]
Oh wait, we don't actually need to know the viewport size anymore - that was back when we used the `texttable` module (now replaced by `prettytable` for Python 3 support). All `blessings` is used for now is to figure out the escape code to clear to the end of the current line.

If we can assume VT-100 compatibility in most cases and… do whatever Windows does for that on there, we could drop the dependency on Blessings altogether.

**Comment by eriklax** [comment]
That sounds even better; I took a quick look but couldn't find where it was used, except in print_waiting_message

**Comment by eriklax** [comment]
https://github.com/halonsecurity/halonctl/commit/58ca13cc7c5019f65648f58a219f2efebe244799

This commit should fix this issue...
